#!/bin/bash
case $(cat /home/mark/.i3/i3_layout) in
    default)    i3-msg layout stacking; echo "stacking" > ~/.i3/i3_layout    ;;
    stacking)   i3-msg layout tabbed; echo "tabbed" > ~/.i3/i3_layout        ;;
    *)          i3-msg layout default; echo "default" > ~/.i3/i3_layout      ;;
esac
